### ISSUE TITLE
第7章最后问题答案探宝

### ISSUE THREAD

**Issue by jianhuaixie** [tianmingyun/MasterBitcoin2CN#21]
- 为什么律师可以随时通过在解锁脚本中选择FALSE来兑换第三个执行路径？
- 在UTXO开采后分别有多少个执行路径可以使用5,35与105天？
- 如果律师失去钥匙，资金是否流失？ 如果91天过去了，你的答案是否会改变？
- 合作伙伴如何每隔29天或89天“重置”一次，以防止律师获得资金？
- 为什么这个脚本中的一些CHECKSIG操作码有VERIFY后缀，而其他的没有？

第一个问题：律师可以随时通过在解锁脚本中选择FALSE来兑换第三个执行路径。第三个执行路径是，2-3签名通不过，90天还没有到，前面两个都是FALSE，就自然到了第三个执行路径了。
第二个问题：我算出来是5个路径。
第三个问题：如果三个合伙人钥匙丢了，然后律师的钥匙也丢了，资金是不是取不出来了？我的答案是没法解锁，取不出来。
第四个问题：合伙人有2个解锁，然后重新签名加锁，这样就相当于重置了。
第五个问题：就看后面还有没有接执行路径。

**Comment by didongke** [comment]
第四个问题：
They 'reset' the clock by moving the funds to a new output before the period ends.
To 'renew' the time, they just need to spend the output by creating a new transaction with exactly the same output script, every time they want to renew it. Because the times use CSV, they are relative timelocks not absolute, so they don't need to be modified for each new transaction. Once a new transaction has been created which spends the output of the old one, that old output cannot be spent a second time so the lawyer must wait for the 30/90 days to elapse on the new transaction, and so on.

**Comment by tianmingyun** [comment]
这部分翻译有误，已经修改
